name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build Linux-amd64
      run: env GOOS=linux GOARCH=amd64 go build -v
        
    - name: Upload Linux-amd64 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Linux-amd64
        path: |
          ./erupe-ce
          ./config.json
          ./www/
          ./savedata/
          ./bin/
          ./RoadShopItems.csv

    - name: Build Windows-amd64
      run: env GOOS=windows GOARCH=amd64 go build -v
      
    - name: Upload Windows-amd64 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows-amd64
        path: |
          ./erupe-ce.exe
          ./config.json
          ./www/
          ./savedata/
          ./bin/
          ./RoadShopItems.csv
